name: ChatPostProcessor
version: 1.0
main: ru.toliak.chatpostprocessor.ChatPostProcessor
author: ToliakPurple
api-version: 1.16

commands:
  chatpostprocessor:
    description: Reloads the configuration file.
    permission: chatpostprocessor.reload
    usage: "Usage: /chatpostprocessor reload"